import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { server } from '../server.mjs';
import { createProject,step } from '../src/recipes.js';

// Isolated port and browser profile: verification never modifies a user's saved project.
await mkdir('artifacts',{recursive:true});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser=await chromium.launch({headless:true,channel:process.env.VIRTUALFAB_BROWSER||(process.platform==='win32'?'msedge':undefined)});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],external=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
  page.on('request',request=>{if(!request.url().startsWith(url)&&!request.url().startsWith('blob:'))external.push(request.url());});
  const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('virtualfab.project.v1')));
  const clickStep=index=>page.locator(`.recipe-card[data-index="${index}"]`).click();
  const loadTemplate=async name=>{
    await page.locator('#template').selectOption(name);
    await page.locator('#load-template').click();
    await page.locator('#confirm-ok').click();
    assert.match(await page.locator('#simulation-status').innerText(),/几何计算完成/);
  };
  await page.goto(url);
  await page.locator('#three-view canvas').waitFor();
  assert.equal(await page.locator('#template option[value="pn"]').innerText(),'异质结');
  await page.locator('#new-project').click();
  assert.match(await page.locator('#confirm-title').innerText(),/新建项目/);
  await page.locator('#confirm-ok').click();
  assert.equal((await saved()).steps.length,25);
  assert.equal(await page.locator('#save-status').innerText(),'尚未保存到文件');
  await page.setViewportSize({width:1440,height:920});
  assert.ok((await page.locator('#three-view').boundingBox()).height>=300,'desktop 3D workspace must remain usable');
  await page.screenshot({path:'artifacts/desktop-layout.png'});
  const libraryBefore=(await page.locator('.library').boundingBox()).width;
  await page.locator('#library-resize').focus();
  await page.keyboard.press('ArrowRight');
  assert.ok((await page.locator('.library').boundingBox()).width>=libraryBefore+15,'keyboard should resize the process library');
  const inspectorBefore=(await page.locator('.inspector').boundingBox()).width;
  const gutter=await page.locator('#inspector-resize').boundingBox();
  await page.mouse.move(gutter.x+gutter.width/2,gutter.y+100);
  await page.mouse.down();
  await page.mouse.move(gutter.x-40,gutter.y+100,{steps:5});
  await page.mouse.up();
  assert.ok((await page.locator('.inspector').boundingBox()).width>=inspectorBefore+30,'drag should resize the inspector');
  assert.ok((await page.locator('.workspace').boundingBox()).width>=420,'resizing must preserve the central workspace');
  await page.screenshot({path:'artifacts/resizable-panels.png'});
  const wideGutter=await page.locator('#inspector-resize').boundingBox();
  await page.mouse.move(wideGutter.x+wideGutter.width/2,wideGutter.y+100);
  await page.mouse.down();
  await page.mouse.move(wideGutter.x-500,wideGutter.y+100,{steps:5});
  await page.mouse.up();
  await page.setViewportSize({width:1100,height:720});
  await page.waitForFunction(()=>document.querySelector('.workspace').getBoundingClientRect().width>=500);
  assert.ok((await page.locator('#three-view').boundingBox()).height>=220,'short desktop windows must retain a usable 3D workspace');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'short desktop content should not overflow horizontally');
  await page.waitForFunction(()=>{const current=document.querySelector('.recipe-card.current').getBoundingClientRect(),strip=document.querySelector('#recipe-cards').getBoundingClientRect();return current.left>=strip.left-1&&current.right<=strip.right+1;});
  await page.screenshot({path:'artifacts/desktop-narrow.png'});
  await page.setViewportSize({width:851,height:720});
  assert.ok((await page.locator('.workspace').boundingBox()).width>=420,'small desktop keeps a usable central pane');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'small desktop does not overflow horizontally');
  await page.setViewportSize({width:1440,height:1000});
  assert.equal(await page.locator('.recipe-card').count(),25);
  await page.locator('[data-panel="results"]').click();
  assert.match(await page.locator('#results-panel').innerText(),/MIM/);
  await page.screenshot({path:'artifacts/desktop-crossbar.png',fullPage:true});
  await page.locator('#view-top').click();
  await page.locator('#three-view canvas').screenshot({path:'artifacts/view-top.png'});
  await page.locator('#view-perspective').click();
  await page.locator('#three-view canvas').screenshot({path:'artifacts/view-perspective.png'});

  // NR9 process playback and actual parameter persistence.
  await page.locator('[data-panel="params"]').click();
  await clickStep(3);
  assert.match(await page.locator('#layer-legend').innerText(),/NR9-3000PY/);
  await page.locator('#param-form [name="thicknessNm"]').fill('2400');
  await page.locator('#param-form button[type="submit"]').click();
  assert.equal((await saved()).steps[3].params.thicknessNm,2400);
  await clickStep(5);
  assert.match(await page.locator('.inspector-title').innerText(),/曝光/);
  const maskPixels=()=>page.evaluate(()=>['mask-target','mask-result'].map(id=>{
    const canvas=document.getElementById(id),pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
    return Array.from({length:canvas.width*canvas.height},(_,i)=>[...pixels.slice(i*4,i*4+4)].join(','));
  }));
  const [target,anticipated]=await maskPixels();
  assert.equal(new Set(target).size,2,'mask preview must show sampled open and covered cells');
  assert.ok(target.every(pixel=>pixel.endsWith(',255')),'mask preview canvas must be opaque');
  assert.deepEqual(anticipated,target,'negative resist preview must reverse exposure into intended openings');
  await page.screenshot({path:'artifacts/mask-exposure.png'});
  await clickStep(7);
  const [lastTarget,developed]=await maskPixels();
  assert.deepEqual(lastTarget,target);
  assert.deepEqual(developed,target,'developed openings must match the sampled mask');
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile mask preview must not overflow');
  assert.ok(await page.locator('#mask-target').isVisible());
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('#toast')).opacity==='0');
  await page.screenshot({path:'artifacts/mobile-mask.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await clickStep(9);
  assert.doesNotMatch(await page.locator('#layer-legend').innerText(),/NR9-3000PY/);

  // Duplicate, reorder, disable, remove and add using the exposed controls.
  await clickStep(2);
  await page.locator('[data-action="duplicate"]').click();
  await page.locator('[data-action="up"]').click();
  await page.locator('[data-action="down"]').click();
  await page.locator('#param-form [name="stepEnabled"]').uncheck();
  await page.locator('#param-form button[type="submit"]').click();
  assert.equal((await saved()).steps[3].enabled,false);
  await page.locator('[data-action="delete"]').click();
  await page.locator('[data-add="anneal"]').click();
  assert.equal((await saved()).steps[3].type,'anneal');
  await page.locator('[data-action="delete"]').click();
  assert.equal(await page.locator('.recipe-card').count(),25);
  await page.locator('#run-all').click();
  await page.locator('#slice-range').fill('4');
  assert.equal(await page.locator('#slice-value').innerText(),'-15.5');
  for(const id of ['view-top','view-front','view-perspective','explode','explode','wafer-view','wafer-view'])await page.locator('#'+id).click();
  await page.reload();
  await page.locator('.recipe-card').first().waitFor();
  assert.equal((await saved()).steps[3].params.thicknessNm,2400);

  // Missing data, evidence validation and a custom local material.
  await page.locator('#open-materials').click();
  await page.locator('[data-material="InON"]').click();
  assert.equal(await page.locator('#prop-bandGap').isDisabled(),true);
  await page.locator('[name="bandGap-evidence"]').selectOption('measured');
  await page.locator('#prop-bandGap').fill('1.7');
  await page.locator('#material-form button[type="submit"]').click();
  assert.match(await page.locator('#material-error').innerText(),/来源和测量条件/);
  await page.locator('[name="bandGap-evidence"]').selectOption('estimated');
  await page.locator('[name="bandGap-note"]').fill('浏览器测试示例，非文献值');
  await page.locator('#material-form button[type="submit"]').click();
  assert.equal((await saved()).materials.find(m=>m.id==='InON').bandGap.value,1.7);
  await page.locator('#new-material').click();
  await page.locator('#material-form [name="id"]').fill('test-n');
  await page.locator('#material-form [name="name"]').fill('测试半导体');
  await page.locator('#material-form [name="polarity"]').selectOption('n');
  await page.locator('#material-form button[type="submit"]').click();
  assert.ok((await saved()).materials.some(m=>m.id==='test-n'));
  const dialogBounds=await page.locator('#materials-dialog').boundingBox(),headingBounds=await page.locator('#materials-dialog .dialog-heading').boundingBox();
  assert.ok(headingBounds.y>=dialogBounds.y&&headingBounds.y+headingBounds.height<=dialogBounds.y+dialogBounds.height,'material dialog heading remains visible after saving');
  await page.screenshot({path:'artifacts/material-library.png',fullPage:true});
  await page.locator('#close-materials').click();

  for(const [name,label]of [['backgate','底栅 FET'],['topgate','顶栅 FET'],['pn','PN 异质结']]) {
    await loadTemplate(name);
    await page.locator('[data-panel="results"]').click();
    assert.ok((await page.locator('#results-panel').innerText()).includes(label));
    if(name==='topgate')await page.screenshot({path:'artifacts/desktop-topgate.png',fullPage:true});
  }
  assert.ok((await saved()).materials.some(m=>m.id==='test-n'));
  await page.locator('[data-view="bands"]').click();
  assert.match(await page.locator('#interface-results').innerText(),/带阶数据不足/);
  await page.screenshot({path:'artifacts/bands-pn.png',fullPage:true});

  // Export/import round trip, invalid import isolation and the manual CSV model.
  const exportEvent=page.waitForEvent('download');
  await page.locator('#save-project').click();
  const exported=await exportEvent;
  await exported.saveAs('artifacts/browser-project.json');
  const exportedData=JSON.parse(await readFile('artifacts/browser-project.json','utf8'));
  assert.deepEqual(exportedData,await saved());
  await page.locator('#project-name').fill('临时改名');
  await page.locator('#project-name').press('Tab');
  await page.locator('#project-file').setInputFiles('artifacts/browser-project.json');
  await page.locator('#confirm-ok').click();
  assert.deepEqual(await saved(),exportedData);
  await page.locator('#project-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":500}')});
  await page.locator('#toast').filter({hasText:'导入失败'}).waitFor();
  assert.deepEqual(await saved(),exportedData);
  await page.locator('[data-view="electrical"]').click();
  await page.locator('#curve-form [name="photocurrentA"]').fill('1e-8');
  await page.locator('#curve-form button[type="submit"]').click();
  const csvEvent=page.waitForEvent('download');
  await page.locator('#export-curve').click();
  await (await csvEvent).saveAs('artifacts/browser-curve.csv');
  assert.equal((await readFile('artifacts/browser-curve.csv','utf8')).trim().split('\n').length,102);
  await page.locator('#curve-form [name="ideality"]').fill('0.1');
  await page.locator('#curve-form [name="temperatureK"]').fill('1');
  let badDownload=false;const onDownload=()=>{badDownload=true;};page.on('download',onDownload);
  await page.locator('#export-curve').click();
  assert.match(await page.locator('#curve-plot').innerText(),/超出数值范围/);
  assert.equal(badDownload,false,'invalid curve parameters must not export previous results');
  page.off('download',onDownload);
  await page.locator('#curve-form [name="ideality"]').fill('1.5');
  await page.locator('#curve-form [name="temperatureK"]').fill('300');
  await page.locator('#curve-form button[type="submit"]').click();
  await page.screenshot({path:'artifacts/electrical-model.png',fullPage:true});
  await page.locator('[data-view="structure"]').click();
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.locator('#library-resize').isHidden(),'mobile layout should hide desktop resize handles');
  assert.equal(await page.locator('.workbench').evaluate(element=>element.style.gridTemplateColumns),'','mobile layout should discard desktop track widths');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile content should not overflow horizontally');
  assert.ok(await page.evaluate(()=>{
    const plot=document.querySelector('#slice-plot'),svg=plot.querySelector('svg'),label=svg.querySelector('.plot-text');
    return svg.getBoundingClientRect().width<=plot.clientWidth&&
      Number.parseFloat(getComputedStyle(label).fontSize)*svg.getScreenCTM().a>=11.5;
  }),'mobile slice must fit the panel and keep labels at readable size');
  await page.waitForFunction(()=>{const current=document.querySelector('.recipe-card.current').getBoundingClientRect(),strip=document.querySelector('#recipe-cards').getBoundingClientRect();return current.left>=strip.left-1&&current.right<=strip.right+1;});
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('#toast')).opacity==='0');
  await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
  await page.locator('[data-view="bands"]').click();
  assert.ok(await page.evaluate(()=>{const plot=document.querySelector('#band-diagram');return plot.scrollWidth>plot.clientWidth;}),'mobile band diagram should scroll within its panel');
  await page.screenshot({path:'artifacts/mobile-bands.png'});
  await page.locator('[data-view="electrical"]').click();
  await page.waitForFunction(()=>{const plot=document.querySelector('#curve-plot');return plot.querySelector('svg')?.getBoundingClientRect().width<=plot.clientWidth;});
  assert.ok(await page.evaluate(()=>{const plot=document.querySelector('#curve-plot'),svg=plot.querySelector('svg'),label=svg.querySelector('.plot-text');return Number.parseFloat(getComputedStyle(label).fontSize)*svg.getScreenCTM().a>=11.5;}),'mobile I-V labels should remain readable');
  await page.screenshot({path:'artifacts/mobile-electrical.png'});

  await page.setViewportSize({width:1440,height:920});
  const derived=createProject('pn');
  for(const key of ['bandGap','affinity'])derived.materials.find(m=>m.id==='Te')[key].evidence='derived';
  derived.materials.find(m=>m.id==='Au').workFunction.evidence='derived';
  await page.locator('#project-file').setInputFiles({name:'derived.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(derived))});
  await page.locator('#confirm-ok').click();
  await page.locator('[data-view="bands"]').click();
  assert.match(await page.locator('#band-diagram').innerText(),/含推导参数/);
  assert.match(await page.locator('#band-diagram').innerText(),/功函数 推导/);

  const large=createProject('crossbar');large.sizeUm=1000;
  await page.locator('#project-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(large))});
  await page.locator('#confirm-ok').click();
  const camera=await page.evaluate(async()=>{
    const {StructureViewer}=await import('/src/viewer.js'),holder=document.createElement('div');
    holder.style.cssText='width:400px;height:300px;position:fixed;left:-1000px';document.body.append(holder);
    const viewer=new StructureViewer(holder),state={sizeUm:1000,resolution:8,cells:Array.from({length:64},()=>[]),substrate:null};
    viewer.update(state,[],4);
    const result={far:viewer.camera.far,distance:viewer.camera.position.distanceTo(viewer.controls.target)};
    viewer.resizeObserver.disconnect();viewer.renderer.dispose();holder.remove();return result;
  });
  assert.ok(camera.far>camera.distance+1000,'large local areas must remain inside the 3D camera range');
  await page.locator('[data-view="structure"]').click();
  await page.locator('#view-perspective').click();
  await page.screenshot({path:'artifacts/large-area.png'});

  const full=createProject('blank');for(let i=0;i<149;i++)full.steps.push(step('clean'));
  await page.locator('#project-file').setInputFiles({name:'full.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(full))});
  await page.locator('#confirm-ok').click();
  await page.locator('[data-add="clean"]').click();
  assert.match(await page.locator('#toast').innerText(),/1–150/);
  await page.locator('[data-panel="params"]').click();
  await page.locator('#params-panel [data-action="duplicate"]').click();
  assert.equal((await saved()).steps.length,150);
  assert.equal(await page.locator('.recipe-card.current').getAttribute('data-index'),'149');
  assert.deepEqual(external,[],'the app must not transmit project data or request remote assets');
  assert.deepEqual(errors,[],'no browser errors');
  console.log('Browser checks passed: WebGL, process editing/replay, templates, materials, local persistence, JSON/CSV, mobile layout.');
} finally {
  await browser?.close();
  await new Promise(resolve=>server.close(resolve));
}
